# Generated by Django 4.2.30 on 2026-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20, verbose_name='شماره گیرنده')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('success', models.BooleanField(default=False, verbose_name='موفق')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
            ],
            options={
                'verbose_name': 'لاگ پیامک',
                'verbose_name_plural': 'لاگ\u200cهای پیامک',
                'ordering': ['-sent_at'],
            },
        ),
    ]
