# Generated by Django 4.2.30 on 2026-05-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, default='Welcome to our store', max_length=200)),
                ('hero_text', models.TextField(blank=True, default='Best products at best prices.')),
                ('hero_banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('about_us', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
