# Generated by Django 4.2.30 on 2026-05-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otprecord',
            options={'verbose_name': 'کد OTP', 'verbose_name_plural': 'کدهای OTP'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='detail',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='otprecord',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
