# Generated by Django 4.2.30 on 2026-05-20 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otprecord_options_remove_address_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='last_sent_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 20, 7, 10, 59, 252044, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
