# Generated by Phase 12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="کد ملی",
            ),
        ),
    ]
