# Generated by Django 4.2.30 on 2026-05-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('base_cost', models.DecimalField(decimal_places=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['name'],
            },
        ),
    ]
