# Generated by Django 4.2.30 on 2026-05-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provinces', models.JSONField()),
            ],
            options={
                'verbose_name': 'منطقه ارسال',
                'verbose_name_plural': 'مناطق ارسال',
            },
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='cost_per_kg',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='free_above',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='max_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='min_days',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shippingzone'),
        ),
    ]
